### PR TITLE
Require fqtools Conda package from UMCCR channel

### PR DESCRIPTION
**Pull request by scwatts**
Enforce requirement by qualifying package spec with the UMCCR channel.

### CODE REVIEW

**Comment by pdiakumis** [comment]
@scwatts you can probably use `umccr::fqtools` to pull it from a specific channel? I think the custom versioning is a bit cumbersome?

**Comment by scwatts** [comment]
Nice one! Didn't know packages could be qualified in that way

**Review by reisingerf — APPROVED** [review]
LGTM

**Review by williamputraintan — APPROVED** [review]
👍

**Pull request merged**
